### ISSUE TITLE
Integrate project.cc in the context of the bare deal.II app template.

### ISSUE THREAD

**Issue by luca-heltai** [ste-dtst/nmpde-project#1] opened 2024-06-21 06:38 UTC

**Comment by ste-dtst** [comment] 2024-06-28 23:48
It should be (almost) done. The debug mode library and executables are correctly generated and run as intended. However, cmake seems unable to find a release version of deal.II on my computer, therefore no release mode file is produced. It is a bit strange, because I have already switched successfully to "make release" in the past when playtesting with tutorials and labs.

Some questions:
- Being HeatParameters<dim> a struct, I moved all its implementation to project.h. Is it correct?
- With the new code structure, am I using the custom namespace nmpdeProject correctly?
- Should I eliminate redundant header inclusions in project.cc?

**Comment by luca-heltai** [comment] 2024-06-29 16:17
> It should be (almost) done. The debug mode library and executables are correctly generated and run as intended. However, cmake seems unable to find a release version of deal.II on my computer, therefore no release mode file is produced. It is a bit strange, because I have already switched successfully to "make release" in the past when playtesting with tutorials and labs.


Try to run 

   cmake -DCMAKE_BUILD_TYPE=DebugRelease .

In the build directory. This is how the cmake of deal.II builds both versions. 

> 
> 
> 
> Some questions:
> 
> - Being HeatParameters<dim> a struct, I moved all its implementation to project.h. Is it correct?

Yes. 

> 
> - With the new code structure, am I using the custom namespace nmpdeProject correctly?
> 
> - Should I eliminate redundant header inclusions in project.cc?

Yes. The .cc file should only contain the implementation.

**Comment by ste-dtst** [comment] 2024-07-02 22:39
Thank you, now both versions are built and run correctly. I've also eliminated redundant headers. If you think everything is ok now, I will close the issue.

**Closed** 2024-07-03 10:17 UTC
